data/cora/cora.content
Loading cora dataset...
Traceback (most recent call last):
  File "/home/ashvinee/Documents/Ferrato/train.py", line 113, in <module>
    adj, features, labels, idx_train, idx_val, idx_test = load_data()
  File "/home/ashvinee/Documents/Ferrato/utils.py", line 23, in load_data
    idx_features_labels = np.genfromtxt("{}{}.content".format(path, dataset),
  File "/home/ashvinee/Documents/Ferrato/venv/lib/python3.8/site-packages/numpy/lib/npyio.py", line 1793, in genfromtxt
    fid = np.lib._datasource.open(fname, 'rt', encoding=encoding)
  File "/home/ashvinee/Documents/Ferrato/venv/lib/python3.8/site-packages/numpy/lib/_datasource.py", line 193, in open
    return ds.open(path, mode, encoding=encoding, newline=newline)
  File "/home/ashvinee/Documents/Ferrato/venv/lib/python3.8/site-packages/numpy/lib/_datasource.py", line 533, in open
    raise IOError("%s not found." % path)
OSError: data/cora/cora.content not found.